---
title: "DATA CRASHBOARD"
output: 
  flexdashboard::flex_dashboard:
    source: embed
    smart: false
runtime: shiny
---

```{r global, include=FALSE}
library( flexdashboard )
library( tidyverse )
library( ggmap )
library( leaflet )
library( viridis )
library( shiny )
library( DT )
library( pander )
library( knitr )
library( rsconnect )

URL <- "https://github.com/DS4PS/Data-Science-Class/blob/master/DATA/TempeTrafficAccidents.rds?raw=true"
dat <- readRDS(gzcon(url( URL )))

dat <- na.omit(dat) # omit any rows with NAs
dat$fatal <- dat$Totalfatalities > 0 
dat$inj <- dat$Totalinjuries > 0 & dat$Totalfatalities == 0
dat$nohurt <- dat$Totalfatalities + dat$Totalinjuries == 0

date.vec   <- strptime( dat$DateTime, format="%m/%d/%y %H:%M" )
dat$hour   <- format( date.vec, format="%H" ) %>% as.numeric()
dat$month  <- format( date.vec, format="%b" )
dat$day    <- format( date.vec, format="%a" )
dat$day365 <- format( date.vec, format="%j" )
dat$week   <- format( date.vec, format="%V" )

dat <- 
  dat %>% 
  mutate( time.of.day = case_when( hour >= 6 & hour <= 9 ~ "Morning Commute", 
                                   hour >= 16 & hour <= 19 ~ "Evening Commute", 
                                   hour >= 14 & hour <= 15 ~ "School Pickup", 
                                   hour >= 9 & hour <= 13 ~ "Work", 
                                   hour >= 20 & hour <= 23 ~ "Night", 
                                   hour <= 5 & hour >= 0 ~ "Midnight to Dawn") )

dat$harm <- ifelse( dat$Totalinjuries > 0 | dat$Totalfatalities > 0, "Harm", "No Harm" )

dat <- 
  dat %>% 
  mutate( d1.substance = case_when( AlcoholUse_Drv1 == "Alcohol" & 
                                      DrugUse_Drv1 == "No Apparent Influence" ~ "Alcohol", 
                                   AlcoholUse_Drv1 == "No Apparent Influence" & 
                                     DrugUse_Drv1 == "Drugs" ~ "Drugs", 
                                   AlcoholUse_Drv1 == "Alcohol" & 
                                     DrugUse_Drv1 == "Drugs" ~ "Alcohol and Drugs", 
                                   AlcoholUse_Drv1 == "No Apparent Influence" & 
                                     DrugUse_Drv1 == "No Apparent Influence" ~ "No Apparent Influence"))

dat <- 
  dat %>% 
  mutate( d2.substance = case_when( AlcoholUse_Drv2 == "Alcohol" & 
                                      DrugUse_Drv2 == "No Apparent Influence" ~ "Alcohol", 
                                    AlcoholUse_Drv2 == "No Apparent Influence" & 
                                      DrugUse_Drv2 == "Drugs" ~ "Drugs", 
                                    AlcoholUse_Drv2 == "Alcohol" & 
                                      DrugUse_Drv2 == "Drugs" ~ "Alcohol and Drugs", 
                                    AlcoholUse_Drv2 == "No Apparent Influence" & 
                                      DrugUse_Drv2 == "No Apparent Influence" ~ "No Apparent Influence"))

dat$age.cat <- case_when( dat$Age_Drv1 >= 0 & 
                            dat$Age_Drv1 <= 18 ~ "Youth", 
                          dat$Age_Drv1 >= 19 & 
                            dat$Age_Drv1 <= 25 ~ "Young Adult", 
                          dat$Age_Drv1 >= 26 & 
                            dat$Age_Drv1 <= 64 ~ "Adult", 
                          dat$Age_Drv1 >= 65 ~ "Senior")
```



Traffic Accidents By Day and Time
=====================================  

Inputs {.sidebar}
-------------------------------------

```{r}
checkboxGroupInput("days", label = h3("Day of Week"), 
    choices = list("Monday"    = "Mon", 
                   "Tuesday"   = "Tue", 
                   "Wednesday" = "Wed", 
                   "Thursday"  = "Thu",
                   "Friday"    = "Fri",
                   "Saturday"  = "Sat",
                   "Sunday"    = "Sun" ),
    selected = c("Fri","Sat","Sun"))

sliderInput("hour", label = h3("Time of Day"), 
            min = 0, max = 23, value = c(6, 12))

# parameters

```

   
Outputs
-------------------------------------

### Traffic Accidents By Day and Time


```{r}

#leaflet
renderLeaflet({
  
  days.of.week <- input$days    # vector will all checked values
  start.time <- input$hour[1]   # sliderInput lower value
  end.time  <-  input$hour[2] 
  
  d2 <-
    dat %>%
    filter( day %in% input$days, 
            hour >= start.time & hour <= end.time )
  
  d2$col.vec <- ifelse( d2$nohurt, "gray20", ifelse(d2$inj, "steelblue", "darkorange") )              
    
  point.size <- d2$Totalinjuries + d2$Totalfatalities

  crash.details <- paste0( "Time: ", d2$DateTime, "<br>",
                     "Total Fatalities: ", d2$Totalfatalities, "<br>",
                     "Total Injuries: ", d2$Totalinjuries, "<br>",
                     "Collision type: ", d2$Collisionmanner)
  
  tempe <- leaflet( ) %>% 
              addProviderTiles( "CartoDB.Positron" )  %>%
              setView( lng=-111.9278, lat=33.39951, zoom=13 )
  
  
  addCircles( tempe, lng=d2$Longitude, lat=d2$Latitude,
              fillColor=d2$col.vec, fillOpacity=0.5, 
              stroke=F, radius=50*(1+0.33*point.size),
              popup=crash.details )


})
```   



Driver Characteristics {data-orientation=rows}
=====================================  

Sidebar {.sidebar}
-------------------------------------
Driver Characteristics
```{r}
sliderInput("d1age", label = h4("Driver 1 Age"), 
            min = 15, max = 100, value = c(18,36) )
sliderInput("d2age", label = h4("Driver 2 Age"), 
            min = 15, max = 100, value = c(18,36) )
selectInput("d1gender", label = h4("Driver 1 Gender"), 
    choices = c("Male","Female", "Unknown"), selected = c("Male"))
selectInput("d2gender", label = h4("Driver 2 Gender"), 
    choices = c("Male","Female", "Unknown"), selected = c("Male"))
radioButtons("d1pedcy", label = h4("Driver 1 Transportation"),
    choices = c("Driver", "Pedalcyclist", "Pedestrian"), selected = c("Driver"))
radioButtons("d2pedcy", label = h4("Driver 2 Transportation"),
    choices = c("Driver", "Pedalcyclist", "Pedestrian"), selected = c("Driver"))

```






Row 
-------------------------------------


### Number of Crashes
  
```{r}
renderValueBox({
  d2 <-
    dat %>%
    filter( Age_Drv1 >= input$d1age[1] & Age_Drv1 <= input$d1age[2], 
            Age_Drv2 >= input$d2age[1] & Age_Drv2 <= input$d2age[2], 
            Gender_Drv1 %in% input$d1gender, 
            Gender_Drv2 %in% input$d2gender, 
            Unittype_One %in% input$d1pedcy, 
            Unittype_Two %in% input$d2pedcy )
  
  crashes <- count( d2 )
  valueBox(crashes, 
           icon = "fa-pencil",
           color = ifelse( crashes > 50, "danger", "primary") )
})
```


### Total Injuries
  
```{r}
renderValueBox({
  d2 <-
    dat %>%
    filter( Age_Drv1 >= input$d1age[1] & Age_Drv1 <= input$d1age[2], 
            Age_Drv2 >= input$d2age[1] & Age_Drv2 <= input$d2age[2], 
            Gender_Drv1 %in% input$d1gender, 
            Gender_Drv2 %in% input$d2gender, 
            Unittype_One %in% input$d1pedcy, 
            Unittype_Two %in% input$d2pedcy )
  
  total.injuries <- sum( d2$Totalinjuries )
  valueBox(total.injuries, 
           icon = "fa-angry",
           color = ifelse( total.injuries > 30, "danger", "primary" ))
})
```

### Total Fatalities
  
```{r}
renderValueBox({
  d2 <-
    dat %>%
    filter( Age_Drv1 >= input$d1age[1] & Age_Drv1 <= input$d1age[2], 
            Age_Drv2 >= input$d2age[1] & Age_Drv2 <= input$d2age[2], 
            Gender_Drv1 %in% input$d1gender, 
            Gender_Drv2 %in% input$d2gender, 
            Unittype_One %in% input$d1pedcy, 
            Unittype_Two %in% input$d2pedcy )

  total.fatalities <- sum( d2$Totalfatalities )
  valueBox( total.fatalities, 
            icon = "fa-briefcase-medical",
            color = ifelse(total.fatalities > 10, "danger", "primary"))
})
```


### Rate of Harm
  
```{r}
renderValueBox({
  d2 <-
    dat %>%
    filter( Age_Drv1 >= input$d1age[1] & Age_Drv1 <= input$d1age[2], 
            Age_Drv2 >= input$d2age[1] & Age_Drv2 <= input$d2age[2], 
            Gender_Drv1 %in% input$d1gender, 
            Gender_Drv2 %in% input$d2gender, 
            Unittype_One %in% input$d1pedcy, 
            Unittype_Two %in% input$d2pedcy )
  
  rate.of.harm <- round(length(which(d2$harm == "Harm"))/count(d2), 3)
  valueBox(rate.of.harm, 
           icon = "fa-pencil",
           color = ifelse(rate.of.harm > 0.5, "danger", "primary"))
})
```




   
Outputs
-------------------------------------

### Traffic Accidents by Driver Characteristics


```{r}

renderLeaflet({
  
  # days.of.week <- input$days    # vector will all checked values
  # start.time <- input$hour[1]   # sliderInput lower value
  # end.time  <-  input$hour[2] 
  
  d2 <-
    dat %>%
    filter( Age_Drv1 >= input$d1age[1] & Age_Drv1 <= input$d1age[2], 
            Age_Drv2 >= input$d2age[1] & Age_Drv2 <= input$d2age[2], 
            Gender_Drv1 %in% input$d1gender, 
            Gender_Drv2 %in% input$d2gender, 
            Unittype_One %in% input$d1pedcy, 
            Unittype_Two %in% input$d2pedcy )
  
  d2$col.vec <- ifelse( d2$nohurt, "gray20", ifelse(d2$inj, "steelblue", "darkorange") )              
    
  point.size <- d2$Totalinjuries + d2$Totalfatalities

  crash.details <- paste0( "Time: ", d2$DateTime, "<br>",
                     "Total Fatalities: ", d2$Totalfatalities, "<br>",
                     "Total Injuries: ", d2$Totalinjuries, "<br>",
                     "Collision type: ", d2$Collisionmanner)
  
  tempe <- leaflet( ) %>% 
              addProviderTiles( "CartoDB.Positron" )  %>%
              setView( lng=-111.9278, lat=33.39951, zoom=13 )
  
  
  addCircles( tempe, lng=d2$Longitude, lat=d2$Latitude,
              fillColor=d2$col.vec, fillOpacity=0.5, 
              stroke=F, radius=50*(1+0.33*point.size),
              popup=crash.details )


})
```   






Drivers 2 {data-orientation=rows}
=====================================  

Sidebar {.sidebar}
-------------------------------------
Driver Characteristics
```{r}
sliderInput("driver.1.age", label = h4("Driver 1 Age"), 
            min = 15, max = 100, value = c(18,36) )
sliderInput("driver.2.age", label = h4("Driver 2 Age"), 
            min = 15, max = 100, value = c(18,36) )
selectInput("driver.1.gender", label = h4("Driver 1 Gender"), 
    choices = c("Male","Female", "Unknown"), selected = c("Male"))
selectInput("driver.2.gender", label = h4("Driver 2 Gender"), 
    choices = c("Male","Female", "Unknown"), selected = c("Male"))
radioButtons("driver.1.pedcy", label = h4("Driver 1 Transportation"),
    choices = c("Driver", "Pedalcyclist", "Pedestrian"), selected = c("Driver"))
radioButtons("driver.2.pedcy", label = h4("Driver 2 Transportation"),
    choices = c("Driver", "Pedalcyclist", "Pedestrian"), selected = c("Driver"))

```






Row 
-------------------------------------


### Number of Crashes
  
```{r}
renderValueBox({
  d2 <-
    dat %>%
    filter( Age_Drv1 >= input$d1age[1] & Age_Drv1 <= input$d1age[2], 
            Age_Drv2 >= input$d2age[1] & Age_Drv2 <= input$d2age[2], 
            Gender_Drv1 %in% input$d1gender, 
            Gender_Drv2 %in% input$d2gender, 
            Unittype_One %in% input$d1pedcy, 
            Unittype_Two %in% input$d2pedcy )
  
  crashes <- count( d2 )
  valueBox(crashes, 
           icon = "fa-pencil",
           color = ifelse( crashes > 50, "danger", "primary") )
})
```


### Total Injuries
  
```{r}
renderValueBox({
  d2 <-
    dat %>%
    filter( Age_Drv1 >= input$d1age[1] & Age_Drv1 <= input$d1age[2], 
            Age_Drv2 >= input$d2age[1] & Age_Drv2 <= input$d2age[2], 
            Gender_Drv1 %in% input$d1gender, 
            Gender_Drv2 %in% input$d2gender, 
            Unittype_One %in% input$d1pedcy, 
            Unittype_Two %in% input$d2pedcy )
  
  total.injuries <- sum( d2$Totalinjuries )
  valueBox(total.injuries, 
           icon = "fa-angry",
           color = ifelse( total.injuries > 30, "danger", "primary" ))
})
```

### Total Fatalities
  
```{r}
renderValueBox({
  d2 <-
    dat %>%
    filter( Age_Drv1 >= input$d1age[1] & Age_Drv1 <= input$d1age[2], 
            Age_Drv2 >= input$d2age[1] & Age_Drv2 <= input$d2age[2], 
            Gender_Drv1 %in% input$d1gender, 
            Gender_Drv2 %in% input$d2gender, 
            Unittype_One %in% input$d1pedcy, 
            Unittype_Two %in% input$d2pedcy )

  total.fatalities <- sum( d2$Totalfatalities )
  valueBox( total.fatalities, 
            icon = "fa-briefcase-medical",
            color = ifelse(total.fatalities > 10, "danger", "primary"))
})
```


### Rate of Harm
  
```{r}
renderValueBox({
  d2 <-
    dat %>%
    filter( Age_Drv1 >= input$d1age[1] & Age_Drv1 <= input$d1age[2], 
            Age_Drv2 >= input$d2age[1] & Age_Drv2 <= input$d2age[2], 
            Gender_Drv1 %in% input$d1gender, 
            Gender_Drv2 %in% input$d2gender, 
            Unittype_One %in% input$d1pedcy, 
            Unittype_Two %in% input$d2pedcy )
  
  rate.of.harm <- round(length(which(d2$harm == "Harm"))/count(d2), 3)
  valueBox(rate.of.harm, 
           icon = "fa-pencil",
           color = ifelse(rate.of.harm > 0.5, "danger", "primary"))
})
```




   
Column
-------------------------------------

### Driver 1


```{r}

renderLeaflet({
  
  # days.of.week <- input$days    # vector will all checked values
  # start.time <- input$hour[1]   # sliderInput lower value
  # end.time  <-  input$hour[2] 
  
  d10 <-
    dat %>%
    filter( Age_Drv1 >= input$driver.1.age[1] & Age_Drv1 <= input$driver.1.age[2], 
            Gender_Drv1 %in% input$driver.1.gender, 
            Unittype_One %in% input$driver.1.pedcy )
  
  d10$col.vec <- ifelse( d10$nohurt, "gray20", ifelse(d10$inj, "steelblue", "darkorange") )              
    
  point.size <- d10$Totalinjuries + d10$Totalfatalities

  crash.details <- paste0( "Time: ", d10$DateTime, "<br>",
                     "Total Fatalities: ", d10$Totalfatalities, "<br>",
                     "Total Injuries: ", d10$Totalinjuries, "<br>",
                     "Collision type: ", d10$Collisionmanner)
  
  tempe <- leaflet( ) %>% 
              addProviderTiles( "CartoDB.Positron" )  %>%
              setView( lng=-111.9278, lat=33.39951, zoom=13 )
  
  
  addCircles( tempe, lng=d10$Longitude, lat=d10$Latitude,
              fillColor=d10$col.vec, fillOpacity=0.5, 
              stroke=F, radius=50*(1+0.33*point.size),
              popup=crash.details )


})
```   



### Driver 2


```{r}

renderLeaflet({
  
  # days.of.week <- input$days    # vector will all checked values
  # start.time <- input$hour[1]   # sliderInput lower value
  # end.time  <-  input$hour[2] 
  
  d11 <-
    dat %>%
    filter( Age_Drv2 >= input$driver.2.age[1] & Age_Drv2 <= input$driver.2.age[2], 
            Gender_Drv2 %in% input$driver.2.gender, 
            Unittype_Two %in% input$driver.2.pedcy )
  
  d11$col.vec <- ifelse( d11$nohurt, "gray20", ifelse(d11$inj, "steelblue", "darkorange") )              
    
  point.size2 <- d11$Totalinjuries + d11$Totalfatalities

  crash.details2 <- paste0( "Time: ", d11$DateTime, "<br>",
                     "Total Fatalities: ", d11$Totalfatalities, "<br>",
                     "Total Injuries: ", d11$Totalinjuries, "<br>",
                     "Collision type: ", d11$Collisionmanner)
  
  tempe2 <- leaflet( ) %>% 
              addProviderTiles( "CartoDB.Positron" )  %>%
              setView( lng=-111.9278, lat=33.39951, zoom=13 )
  
  
  addCircles( tempe2, lng=d11$Longitude, lat=d11$Latitude,
              fillColor=d11$col.vec, fillOpacity=0.5, 
              stroke=F, radius=50*(1+0.33*point.size2),
              popup=crash.details2 )


})
```   





About
===================================== 



Row 
-------------------------------------

### About this Dashboard


### Dashboard Author


Row
-------------------------------------

DATA DICTIONARY


```{r}
data.dictionary <- 
structure(list(column = structure(c(13L, 7L, 32L, 19L, 6L, 8L, 
15L, 22L, 21L, 14L, 5L, 17L, 31L, 20L, 27L, 1L, 11L, 23L, 25L, 
29L, 3L, 9L, 28L, 2L, 12L, 24L, 26L, 30L, 4L, 10L, 16L, 18L), .Label = c("Age_Drv1", 
"Age_Drv2", "AlcoholUse_Drv1", "AlcoholUse_Drv2", "Collisionmanner", 
"CrossStreet", "DateTime", "Distance", "DrugUse_Drv1", "DrugUse_Drv2", 
"Gender_Drv1", "Gender_Drv2", "Incidentid", "Injuryseverity", 
"JunctionRelation", "Latitude", "Lightcondition", "Longitude", 
"StreetName", "SurfaceCondition", "Totalfatalities", "Totalinjuries", 
"Traveldirection_One", "Traveldirection_Two", "Unitaction_One", 
"Unitaction_Two", "Unittype_One", "Unittype_Two", "Violation1_Drv1", 
"Violation1_Drv2", "Weather", "Year"), class = "factor"), type = structure(c(1L, 
3L, 1L, 2L, 2L, 1L, 2L, 1L, 1L, 2L, 2L, 2L, 2L, 2L, 2L, 1L, 2L, 
2L, 2L, 2L, 2L, 2L, 2L, 1L, 2L, 2L, 2L, 2L, 2L, 2L, 1L, 1L), .Label = c("numeric", 
"text", "timestamp"), class = "factor"), label = structure(c(10L, 
6L, 29L, 16L, 5L, 7L, 12L, 19L, 18L, 11L, 4L, 14L, 28L, 17L, 
24L, 1L, 1L, 20L, 22L, 26L, 2L, 8L, 25L, 1L, 1L, 21L, 23L, 27L, 
3L, 9L, 13L, 15L), .Label = c("", "Alcohol Use 1 ", "Alcohol Use 2", 
"Collision Manner", "Cross-street", "Date Time", "Distance from Intersection", 
"Drug Use 1", "Drug Use 2", "Incident ID", "Injury Severity ", 
"Junction Relation", "Latitude", "Lighting Conditions", "Longitude", 
"Street Name", "Surface Condition", "Total Fatalities", "Total Injuries", 
"Travel Direction", "Travel Direction Two", "Unit Action One", 
"Unit Action Two", "Unit Type One", "Unit Type Two", "Violation  One", 
"Violation Two", "Weather", "Year"), class = "factor"), description = structure(c(21L, 
2L, 23L, 17L, 14L, 9L, 11L, 20L, 19L, 10L, 4L, 18L, 15L, 16L, 
3L, 1L, 1L, 7L, 13L, 12L, 5L, 6L, 3L, 1L, 1L, 8L, 13L, 12L, 5L, 
6L, 22L, 22L), .Label = c("", "Date and time that the crash occurred.", 
"Driver, Passenger, Pedestrian, Pedalcyclist or Driverless.", 
"Identifies the manner in which two vehicles initially came into contact.", 
"Indicates whether alcohol was a contributing factor in the crash or not.", 
"Indicates whether drug use was a contributing factor in the crash or not.", 
"The direction the unit was traveling before the incident occurred,", 
"The direction the unit was traveling before the incident occurred.", 
"The distance, in feet, that the crash occurred from the cross-street.  This distance is expressed in feet with positive numbers being either north or east of the intersection and negative numbers being either south or west of the intersection, based on the orientation of the street that the incident occurred on. (i.e. Baseline Rd runs in an E/W direction and so a negative number would be west of the intersection and a positive number would be east of the intersection).", 
"The highest severity of injury of all persons involved in the crash.\n\nNo Injury - No complaint or treatment was required by the person.\n\nPossible Injury - Complaint of pain without visible injury. Includes â\200“ momentary unconsciousness, claim of injuries not evident, limping, complaint of pain, nausea or hysteria.\n\nNon-Incapacitating Injury - Any injury, other than a fatal injury or an incapacitating injury, which is evident to observers at the scene of the crash in which the injury occurred.\nExamples: contusions (bruises), laceration, bloody nose, lump on head, or abrasions.\n\nIncapacitating Injury - Any injury, other than a fatal injury, which prevents the injured person from walking, driving or normally continuing the activities the person was capable of performing before the injury occurred. Often defined as â\200œneeding help from the scene.â\200\235 Includes: severe lacerations, broken or distorted limbs, skull or chest injuries, abdominal injuries, unconsciousness when taken from the crash scene.\n\nFatal Injury - Any injury that results in death within 30 days after the crash occurred.\n", 
"The location of the crash in relation to a junction, either an intersection or connection between a driveway and a roadway.", 
"The main violation/behavior of the unit that contributed to the crash.", 
"The maneuver, or last action, of the unit before the crash.", 
"The nearest intersecting street or road.", "The prevailing (most significant) atmospheric conditions that existed at the time of the crash.", 
"The roadway surface condition at the time and place of a crash.", 
"The street that the crash occurred on.", "The type/level of light that existed at the time of the crash.", 
"Total number of persons with fatal injuries involved in the crash.", 
"Total number of persons with non-fatal injuries involved in the crash.", 
"Unique incident ID number assigned by Arizona Department of Transportation (ADOT).", 
"Used to specify the precise location of the crash.", "Year that the crash occurred."
), class = "factor")), class = "data.frame", row.names = c(NA, 
-32L))
```

```{r}
dd.simple <-
  data.dictionary %>%
  select( column, description )
#kable( dd.simple )  # markdown table, from knitr package
pander( dd.simple )  # html table, from pander package
```



Data
=====================================  

```{r}
# library( DT )

these.buttons <- c( 'copy', 'csv', 'pdf', 'print' )

renderDataTable({
  datatable(dat[1:100,], filter='bottom', rownames=FALSE, 
           #options=list( pageLength=5, autoWidth=TRUE ),
           fillContainer=TRUE, 
           style="bootstrap",
           class='table-condensed table-striped',
           extensions = 'Buttons', 
           options=list( dom='Bfrtip', 
                         buttons=these.buttons  ) )
})
```





